# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Get Core & Configure
    before: |
      wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
      chmod u+x hyperexecute

  - name: Setup LT creds
    command: |
      export LT_USERNAME=surajsahu124
      export LT_ACCESS_KEY=JYvphyRIMkzZI44wLeVZB3PHOSKcP7oqdkFYSQccX8YLShY6vx
      
    init: |
      echo "Performing test"
      ./hyperexecute --config yaml/win11/.hyperexecute_autosplit.yaml --download-artifacts --force-clean-artifacts
      echo "Test completion"
