# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Setup & Run HyperExecute
    command: |
      # Download HyperExecute CLI
      wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
      chmod u+x hyperexecute

      # Set LT credentials
      export LT_USERNAME=sahusuraj4292
      export LT_ACCESS_KEY=JsLzh3dkbNs7zLOzrcprQoa86Ui9plCa2V421ZNVOJbIfyoOHdm

      # Run HyperExecute
      ./hyperexecute --config yaml/linux/.hyperexecute_autosplits.yaml --download-artifacts --force-clean-artifacts


      
